language: go
go:       "1.11"

env:
  global:
  - GO111MODULE=on

  # REVIEWDOG_GITHUB_API_TOKEN
  - secure: "t48yClc+qmha3iyjwMwJnYemOTf5SwdQj5I+70/gSwNhVPt+8tgRuAbb3NiWlSSNulFpBxyjaslNZU/XBQf4ZxsDuVGQozHyn3B7lLP9As3yYkgiumuOMCESm9z48VnBS8Qj+8nnQaaTebxyQe03DM9x26q5a5xjlOen/YroIErw2OYgs/UsrYeWjJUY5g60vDuoaxJ6CVDVf2S2ChHx407WcYccBQ8q3AgBkxmiTlW7Ai8mE34P5nQGsgO/3vkiPh0U3nAZl7lZ8lClbY3c7GZc7awT47+l3ZdBxk5KyxwFLQYJDVgpzuFROfWy2Idxw02xAoaowappOEYy8ER/zXY2osvOOhoHjgeWK/dVLOYSUQdEMfpotl3e+riS6IdX0uzuQjeIzDCDpHhWdHOaZLENREMx2RGKvnUHDPmMxrdDObTpwdtOmEoR0rY259m25YnVMYlz9raVOJzZ++v+c4mHbxfD53xzexorZswO49WG/mlt9stOdMgh8htm2Y06vFe4e8SDrCEEs+a0S4S2XAyNbD2LkaKhgXaTbDnz5kZ87xX//fbz4AjUavWYVVpvvH74ghPMW47risaLjfNklCdiKi7O/K7S6D/1mfw93K4YmbOwPRnnHhjR2AXOUlDoC28QGVMuY8kK4Oj2FCBxMRH/9xqYPUpDCl/OcQ6g/Po="

cache:
  directories:
  - $GOPATH/pkg/mod

jobs:
  include:
  - name: 'lint'
    before_script:
    - go get github.com/izumin5210/gex/cmd/gex
    - gex --build
    script: gex reviewdog -reporter=github-pr-review
    if: type = 'pull_request'

  - name: 'test'
    script: go test -v -coverpkg ./... -coverprofile coverage.txt -covermode atomic ./...
    after_success: bash <(curl -s https://codecov.io/bash)
    if: type != 'pull_request'
